### ISSUE TITLE
Add sequences to tracker

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#1]
## Value statement
As an **editor** 
I need **a list of sequence cards and a summery of added sequence length** 
so that **I can see, how many sequence I have, what the description is and what length the sequence has** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2020-08-31 um 10 06 08](https://user-images.githubusercontent.com/54703643/91697548-9c0ab280-eb71-11ea-81b8-6b8bbe351bd6.png)

## Acceptance criteria
- [x] with no sequence card visibile, the input block is at top
- [x] input field is always visible under last sequence card
- [x] With "Speichern" the Card will be added to sequence, at the end of list
- [x] With "Löschen" the input fields will be resetet
- [x] all inputs needs to be filled before save is possible
- [x] At bottom, there is the summery length of all sequences lengths

## Tasks
- [x]  Create feature branch
- [x]  Create Sequence component in Storybook
- [x]  Write component tests
- [x]  Add components to app (feature implementation with state)
- [x]  Add missing styles

## Size
(large)
