### ISSUE TITLE
Update Edit function

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#10]
## Value statement
As an **editor** 
I need **to edit a SequenceCard** 
so that **I can update the timecode or other information** 

## Description
- Update the edit function for newly added fields
- Card to edit same as newCard Layout

## Acceptance criteria
- [ ] The form is found at the path `"/edit/:id"`
- [ ] The form has the value passed from the sequenceCard found under :id
- [ ] The button is disabled until title and timecode inputs are filled
- [ ] The min field is not required (should then be 0)
- [ ] The sec and frames field is required
- [ ] The form reacts on submit (Enter key or button press)
- [ ] After submit change back to page with all cards

## Tasks
- [ ] Add routing
- [ ] Add Button for edit
- [ ] load sequenceCard information from localStorage into form
- [ ] behavior, if :id not available, because user manually navigate to `/edit/:id`
- [ ] Write component tests
- [ ] Write integration tests w/ Cypress
- [ ] Test on mobile and desktop

## Size
(large)
