### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#11]
## Value statement
As an **editor** 
I need **a page for overall settings for general information** 
so that **I can set he stadium visitors number, the total length for summery** 

## Description
![Bildschirmfoto 2020-08-27 um 23 19 19](https://user-images.githubusercontent.com/54703643/91496024-be73a600-e8bb-11ea-9ff5-d83f1e6431ac.png)

## Acceptance criteria
- [ ] the path is /settings
- [ ] No field is required
- [ ] The button is disabled until one input is filled
- [ ] The min field is not required (should then be 0)
- [ ] The sec and frames field is required
- [ ] The form reacts on submit (Enter key or button press)

## Tasks
- [ ] Add routing
- [ ] Add current length input field
- [ ] add visitors length input field
- [ ] at save, save information in localStorage
- [ ] at load, load information from localStorage into fields
- [ ] Write component tests
- [ ] Write integration tests w/ Cypress

## Size
(medium)
