### ISSUE TITLE
Delete Gameday button

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#12]
## Value statement - a requirement, not a solution
As an **editor** 
I need **a delete Gamedate button** 
so that **i can start a new Gameday** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2020-08-27 um 23 28 25](https://user-images.githubusercontent.com/54703643/91496767-02b37600-e8bd-11ea-8b98-ed2053e870fe.png)

## Acceptance criteria
- [x] Button is red
- [x] after deletion, all gameday information is deleted
- [x] After clicking, it it comes up a "confirmation" button, so that accidental deletion is not possible

## Tasks
- [x] delete all information from localStorage and state

## Size
(large)
