### ISSUE TITLE
Overview of summary time

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#13]
## Value statement
As an **editor** 
I need **an overview of time of summary** 
so that **I have an overview of the time the summary is currently long** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2020-08-27 um 23 36 50](https://user-images.githubusercontent.com/54703643/91497443-570b2580-e8be-11ea-836a-d2fd4289ea8e.png)

## Acceptance criteria
- [ ] on the left side it shows  the current time, added in the settings page
- [ ] if time is not set in setting page, it shows 0mins
- [ ] in the middle it shows the added up time from all active sequences
- [ ] on the right side it shows the time is left, if time was added in settings page
- [ ] green, if we on time
- [ ] red, if we are over time

## Tasks
- [ ] get time from localStorage
- [ ] check, if time set in localStorage, if not, set time to 0
- [ ] build logic for the calculation of the remaining time

## Size
(large)
