### ISSUE TITLE
TimeCode Tracker

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#14]
## Value statement
As an **editor** 
I need **inputs, where I can add 3 different timecodes** 
so that **the timecodes add up and the addition result is shown** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2020-08-28 um 19 28 28](https://user-images.githubusercontent.com/54703643/91595953-ad32a400-e964-11ea-9c41-3b2b126547ff.png)

## Acceptance criteria
- [x] the inputs are empty at start
- [x] at enter the input field, the integer keyboard is shown
- [x] input is set, when user leaves input field or hits enter
- [x] if one input is set, it shows a total length
- [x] enter sets the focus to next input
- [x] input value is 042517 for min:sec:fr ( 04:25:17 ) 
- [x] input value 3217 converts to ( 00:32:17 )
- [x] "Länge Spiel" shows addition result from "Halbzeit 1" & "Halbzeit 2"
- [x] "Länge gesamt" shows addition result from "Halbzeit 1", "Halbzeit 2" & "O-Töne"

## Tasks
- [x]  Create feature branch
- [x]  Create component in Storybook
- [x]  Write component tests
- [x]  Add components to app (feature implementation with state)
- [x]  Add missing styles

## Size
(large)
