### ISSUE TITLE
Timecode formating at typing

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#18]
## Value statement - a requirement, not a solution
As an **editor** 
I need **a automatic timecode formating in input field when typing** 
so that **I can see a lot better, where I am when I enter the timecode** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2020-09-04 um 17 31 24](https://user-images.githubusercontent.com/54703643/92256799-76b0d800-eed4-11ea-8636-201218211a5b.png)

## Acceptance criteria
- [x] Placeholder shows user the format "hh:mm:ss:ff" in Timecode Input
- [x] after every two numbers, when the next number is typed, a colon is inserted
- [x] when deleting a number and colon would be left, colon is deleted too
- [x] if timecode has only zeros, error is shown

## Tasks
- [x] implementing helper function for formating

## Size
(large)
