### ISSUE TITLE
Show add up timescodes at bottom

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#2]
## Value statement
As an **editor** 
I need **the sequence timecodes to add up** 
so that **I can see, how long the hole summary is** 

## Description (Text, Scribble, Wireframe, Design)
![Bildschirmfoto 2020-08-26 um 14 45 16](https://user-images.githubusercontent.com/54703643/91305062-c42d9680-e7aa-11ea-9d92-87649b8e07c3.png)

## Acceptance criteria
- [ ] At the bottom the added time from all SequenceCards is shown 

## Tasks
- [ ] Create feature branch
- [ ] Create BottomTotalLenght component in Storybook
- [ ] Write component tests
- [ ] Write add-up logic
- [ ] Add components to app (with add-up logic)

## Size
(large)
