### ISSUE TITLE
Add ReactRouter

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#24]
## Value statement - a requirement, not a solution
As an **editor** 
I need **the possibility to navigate through the app** 
so that **I can use the timecode input on anthoter page and see all important timecodes on the dashboard** 

## Description (Text, Scribble, Wireframe, Design)

<img width="264" alt="Bildschirmfoto 2020-09-19 um 09 17 17" src="https://user-images.githubusercontent.com/54703643/93661559-f3a58b00-fa58-11ea-9ef0-e55e2dfd7885.png">

## Acceptance criteria
- [ ] the 1st halftime Link shows length of sequences of first half
- [ ] and links to sequence page with sequence from first half-time
- [ ] the 2st halftime Link shows length of sequences of second half
- [ ] and links to sequence page with sequence from second half-time
- [ ] the interview Link shows length of sequences of interview sequence
- [ ] and links to interview page with sequence with interviews
- [ ] the special Link shows number of "special" sequences
- [ ] the info link links to the summary page
- [ ] a little blue border shows the active page

## Tasks
- [ ] build navBar component
- [ ] install react router
- [ ] build page components
- [ ] build header component
- [ ] build Timecode Bubble component
- [ ] link Add Timecode and Settings to pages

## Size
(large)
