### ISSUE TITLE
More inputs for create sequence

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#25]
## Value statement - a requirement, not a solution
As an **editor** 
I need **more inputs at /create Page** 
so that **I can create sequences for first half-time, second-half-time etc)** 

## Description (Text, Scribble, Wireframe, Design)
<img width="375" alt="Bildschirmfoto 2020-09-19 um 20 53 57" src="https://user-images.githubusercontent.com/54703643/93686980-47948c00-faba-11ea-8889-c74241e48ecc.png">
<img width="401" alt="Bildschirmfoto 2020-09-19 um 20 54 02" src="https://user-images.githubusercontent.com/54703643/93686981-4a8f7c80-faba-11ea-952f-f63ad8b49a7b.png">

## Acceptance criteria
- [x] Inputs are at first not checked
- [x] one needs to be chosen
- [x] Only 1st and 2nd options needs all inputs
- [ ] Interview has only description and duration input
- [ ] Special has only description and real timecode input
- [ ] if Interview is checked, the Tor and Rote Karte tags disappear and appear, when 1st or 2nd are checked again

## Tasks
- [ ] every check needs to be pushed in separate array in big object
- [ ] add more checks

## Size
(large)
