### ISSUE TITLE
Timestamps in between

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#26]
## Value statement - a requirement, not a solution
As an **editor** 
I need **length summaries after every active sequence** 
so that **I can see how long the game summary is at this moment** 

## Description (Text, Scribble, Wireframe, Design)
<img width="451" alt="Bildschirmfoto 2020-09-19 um 21 08 50" src="https://user-images.githubusercontent.com/54703643/93687233-5419e400-fabc-11ea-9b37-fa6c7f866336.png">

## Acceptance criteria
- [ ] Should add all previous active cards together
- [ ] Should show 00:00:00 if Card is deactivated

## Tasks
- [ ] write sum up algorithm

## Size
(large)
