### ISSUE TITLE
Toggle Sequence

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#3]
## Value statement
As an **editor** 
I need **to deactivate or activate the SequenceCard** 
so that **I can see, how long the summary is without the deactivated sequence** 

## Description
![Bildschirmfoto 2020-08-26 um 15 28 34](https://user-images.githubusercontent.com/54703643/91309456-e62a1780-e7b0-11ea-97af-02b346a94c3d.png)

## Acceptance criteria
- [x] Active and deactive SequenceCards are both always visible
- [x] SequenceCard is active by default
- [x] Deactivated SequenceCard is greyed out and not added up in TotalLength
- [x] At the bottom the added time from all **active** SequenceCards is shown 

## Tasks
- [x] Create feature branch
- [x] Create Toggle Component
- [x] Add Toggle Logic
- [x] Change "add-up" logic, with only active SquenceCards
- [x] Styling
- [x] Write component tests
- [x] Write integration tests w/ Cypress

## Size
(middle)
