### ISSUE TITLE
Create new SequenceCard

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#4]
## Value statement
As an **editor** 
I need **to add new Sequences** 
so that **I can see, how long the summary with all added sequences is** 

## Description
**Add (plus) layout**
![Bildschirmfoto 2020-08-26 um 15 41 02](https://user-images.githubusercontent.com/54703643/91310759-8fbdd880-e7b2-11ea-96d0-3cf6493a2376.png)

**New Sequence Form**
![Bildschirmfoto 2020-08-26 um 15 52 03](https://user-images.githubusercontent.com/54703643/91312070-18894400-e7b4-11ea-83c4-56fc71773e88.png)

## Acceptance criteria
- [ ] The form is found at the path `"/create"`
- [ ] The button is disabled until title and timecode inputs are filled
- [ ] The min field is not required (should then be 0)
- [ ] The sec and frames field is required
- [ ] The form reacts on submit (Enter key or button press)
- [ ] The first input has focus at start and after submit
- [ ] The form is cleared after submit
- [ ] The new card is added at the end

## Tasks
- [ ] Create PlusSign component
- [ ] Add routing
- [ ] Create form component
- [ ] Styling
- [ ] Write component tests
- [ ] Write integration tests w/ Cypress
- [ ] Test on mobile and desktop

## Size
(large)
