### ISSUE TITLE
Save state locally

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#5]
## Value statement
As an **editor** 
I need **to keep my SequenceCards through sessions** 
so that **I don't lose my information how long the current summary is** 

## Description (Text, Scribble, Wireframe, Design)
- No visible impact

## Acceptance criteria
- [x] on refresh/reload the sequences stays

## Tasks

- [x] Create services for localStorage
- [x] Implement save/load for cards
- [x] Test on desktop and mobile
- [x] every change on the state cards should trigger a save to localStorage
- [x] Reload of the page should load cards from localStorage

## Size
(medium)
