### ISSUE TITLE
Edit Sequence

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#6]
## Value statement
As an **editor** 
I need **to edit a SequenceCard** 
so that **I can update the timecode or other information** 

## Description
![Bildschirmfoto 2020-08-27 um 23 11 48](https://user-images.githubusercontent.com/54703643/91495346-bb2bea80-e8ba-11ea-9f97-c1da76a2f924.png)

- Card to edit same as newCard Layout

## Acceptance criteria
- [x] the values will be inserted in form, after hitting the edit button
- [x] all validation will work
- [x] deactivated cards can be edited to

## Tasks
- [x] Add Button for edit
- [x] Write integration tests w/ Cypress
- [x] Test on mobile and desktop

## Size
(large)
