### ISSUE TITLE
Add more input fields in CreateSequence

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#7]
## Value statement
As an **editor** 
I need **to add more important information in the "create new sequences" process** 
so that **after the game, I have all the important information at my fingertips** 

## Description
![Bildschirmfoto 2020-08-31 um 11 01 09](https://user-images.githubusercontent.com/54703643/91702633-4afebc80-eb79-11ea-9c40-f6a630dd6175.png)

## Acceptance criteria
- [x] additional input fields are hidden by default
- [x] if "tag" Tor or Rote Karte is clicked, it opens an additional input overall area
- [x] all fields are required in the additional area
- [x] the input values are staying, when "tag" is changing from Tor to Rote Karte
- [x] Delete Button clears form, and closes additional field
- [x] Save button clears form, and closes addition field

## Tasks
- [x] Add additional input fields
- [x] Add toggle logic
- [x] Styling
- [x] Write component tests
- [x] Write integration tests w/ Cypress
- [x] Test on mobile and desktop

## Size
(large)
