### ISSUE TITLE
Update lower third timecodes after de or activate sequence card

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#8]
## Value statement
As an **editor** 
I need **that lowerhird timecodes automatically update when earlier timecodes are changing ** 
so that **there are no wrong timecodes at the end** 

## Description
- no visible impact except for that the timecodes are correct

## Acceptance criteria
- [x] after a SequenceCard is de or activated, all lower third timecodes need to be correct updated 

## Tasks
- [x] Add new timecode logic
- [x] Test on mobile and desktop

## Size
(large)
