### ISSUE TITLE
Summary page

### ISSUE THREAD

**Issue by mpagels** [mpagels/capstone-project#9]
## Value statement
As an **editor** 
I need **a summarized page with all important information** 
so that **I can pass on all necessary information to Cologne** 

## Description
![Bildschirmfoto 2020-08-26 um 17 49 59](https://user-images.githubusercontent.com/54703643/91326411-9a816900-e7c4-11ea-868c-715d9d7d3790.png)

## Acceptance criteria
- [ ] Shows current length of summary (add up all active Sequences) 
- [ ] If there was/were a goal/s in game show all goals, the scorer and the in-timecode and out-timecode of lowerthird
- [ ] If there was/were a red card in game show all players and the in-timecode and out-timecode of lowerthird

## Tasks
- [ ] get localStorage
- [ ] filter all information
- [ ] show information
- [ ] Write integration tests w/ Cypress
- [ ] Test on mobile and desktop

## Size
(medium)
